### ISSUE TITLE
How did you made translated recipes names for specific language?

### ISSUE THREAD

**Issue by Blueberryy** [T8RIN/FridgeXLight#2]
Is it getting translation for names from some database?

**Comment by T8RIN** [comment]
> Is it getting translation for names from some database?

Yes, I use two databases, one for Russian, the other for English, they are identical, the only difference is in the language

**Comment by Blueberryy** [comment]
> > Is it getting translation for names from some database?
> 
> Yes, I use two databases, one for Russian, the other for English, they are identical, the only difference is in the language

Ah okay
